// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArfpImj5jjYglZhnTRDyhSxXgvqrpdJ9U',
    appId: '1:816597884276:web:acb3d281e1cb4d98836021',
    messagingSenderId: '816597884276',
    projectId: 'post-pro-v1',
    authDomain: 'post-pro-v1.firebaseapp.com',
    storageBucket: 'post-pro-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDABkTFPfZIuXMOJAUYLPVCEPLT5D9HtQ',
    appId: '1:816597884276:android:a59f991f594d7f71836021',
    messagingSenderId: '816597884276',
    projectId: 'post-pro-v1',
    storageBucket: 'post-pro-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1x-TB_z2BFDHrLeVwrYDEkqGjaPhdtOA',
    appId: '1:816597884276:ios:b7b2ed8c3b983886836021',
    messagingSenderId: '816597884276',
    projectId: 'post-pro-v1',
    storageBucket: 'post-pro-v1.firebasestorage.app',
    iosBundleId: 'com.example.postpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1x-TB_z2BFDHrLeVwrYDEkqGjaPhdtOA',
    appId: '1:816597884276:ios:b7b2ed8c3b983886836021',
    messagingSenderId: '816597884276',
    projectId: 'post-pro-v1',
    storageBucket: 'post-pro-v1.firebasestorage.app',
    iosBundleId: 'com.example.postpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArfpImj5jjYglZhnTRDyhSxXgvqrpdJ9U',
    appId: '1:816597884276:web:426b79ca6fa3d697836021',
    messagingSenderId: '816597884276',
    projectId: 'post-pro-v1',
    authDomain: 'post-pro-v1.firebaseapp.com',
    storageBucket: 'post-pro-v1.firebasestorage.app',
  );
}
